### ISSUE TITLE
New Navidrome albums appear empty

### ISSUE THREAD

**Issue by Insprill** [gitbobobo/StreamMusic#588]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
When adding a new album in Navidrome, StreamMusic will show the album and it's art on the artist page, but when clicking on it, it's empty.

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
1. Add a new album to Navidrome then do a quick scan.
2. Go to that artist in StreamMusic and find the new album.
3. Click on it. It will be empty.

**Expected behavior (期望行为)**
The new album should be loaded correctly.

**Screenshots (截图)**
Album as seen from the artist page:
![image](https://github.com/user-attachments/assets/4b1dcae7-2ca2-4fd4-866b-5e944c3cb52e)
Album after clicking on it:
![image](https://github.com/user-attachments/assets/2d389624-c927-4550-8f06-423457a09477)
Album in the Navidrome UI (it also shows fine in all other players):
![image](https://github.com/user-attachments/assets/7603a07a-7c0b-44f4-af05-305e6359823a)

**Platform and Device Info (操作系统及设备信息)**
 - OS: IOS v16.7.10
 - StreamMusic: v1.3.1
 - Navidrome: v0.53.2

**Music Server Type (音乐服务器类型)**

- [ ] Direct Mode（直连模式）
- [x] Library Mode（媒体库模式）

**Comment by gitbobobo** [comment]
in library mode，if you delete or modify some files and add some files, the Clients may not recognize all changes to the songs because the current automatic incremental update only synchronizes data based on the total number of songs. Therefore, if this situation occurs, it is best to manually perform a full synchronization of the data.
